version: '3.8'

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  service-currency-map:
    container_name: service-currency-map
    build:
      context: ./cbrRate
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Kirill
    ports:
      - "8081:8081"

  service-currency-client:
    container_name: service-currency-client
    build:
      context: ./CurrencyRateClient
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Kirill
    depends_on:
      - service-currency-map
    ports:
      - "8082:8082"

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    networks:
     - kafka-net
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:19092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:19092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:19092"
    depends_on:
      - "kafka"

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    restart: on-failure
    volumes:
      - ./kowl_config:/etc/kowl/
    ports:
      - "8088:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    networks:
      - kafka-net
    depends_on:
      - kafka
      - zookeeper
